apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: client-server-binding
subjects:
  - kind: ServiceAccount
    name: endpoints-reader
    namespace: adhoc
roleRef:
  kind: ClusterRole
  name: server-role
  apiGroup: rbac.authorization.k8s.io
