// Code generated by goctl. DO NOT EDIT!
// Source: hello.proto

package server

import (
	"context"

	"zero-examples/gateway/internal/logic"
	"zero-examples/gateway/internal/svc"
	"zero-examples/gateway/types/hello"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	hello.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) Ping(ctx context.Context, in *hello.Request) (*hello.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
