// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"timeout/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/slow/:name",
				Handler: SlowHandler(serverCtx),
			},
		}, rest.WithTimeout(5000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/fast/:name",
				Handler: FastHandler(serverCtx),
			},
		},
	)
}
