// Code generated by goctl. DO NOT EDIT.
package types

type JwtTokenRequest struct {
}

type JwtTokenResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type GetUserRequest struct {
	UserId string `json:"userId"`
}

type GetUserResponse struct {
	Name string `json:"name"`
}
